name: Build

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Build
        run: ./build.ps1
        shell: pwsh
      - name: Test
        run: ./Pester.Test.ps1
        shell: pwsh