name: CI

on: push

jobs:
  lint:
    name: Run PSSA
    runs-on: windows-latest
    steps:
    - uses: devblackops/github-action-psscriptanalyzer@master

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build
        run: |
          pwd
          ./build.ps1
        shell: pwsh
      - name: Test
        run: ./Pester.Test.ps1
        shell: pwsh
      - name: Install Pester
        shell: pwsh
        run: Install-Module Pester -Force
      - name: Install Pester
        shell: pwsh
        run: Invoke-Pester ./Pester.Tests.ps1 -EnableExit
